import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/Header";

import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import HeroSection from "@/components/HeroSection";

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Grindle - One Stop Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <ClerkProvider 
    appearance={{
      baseTheme: dark,
    }}>

    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${inter.className} `}
      >
       <ThemeProvider 
       attribute="class"
       defaultTheme="dark"
       enableSystem
       disableTransitionOnChange
      >
        

        <Header/>

        <main className="min-h-screen">
        {children}
        </main>

        <footer className="bg-muted/50 py-12">
          <div className="container mx-auto px-4 text-center text-gray-200">Developed by Ritik</div>
        </footer>
      
        </ThemeProvider>

     
      </body>
    </html>
    </ClerkProvider>
    </>
  );
}
